### PR TITLE
feat: carbon reporting

### PR DESCRIPTION
**Pull request by joshghent**
Add carbon reporting
Updated social card

### CODE REVIEW

**Comment by PatrickHeneise** [comment]
Thanks @joshghent for the report.

The Action looks for the current branch metadata, as far as I can tell, your pull-request checks runs on `main` (`master`) but should be running on the feature-branch instead. Try this:

```
on:
  push:
    branches:
      - '**'
      - '!main'
```

That'll run the PR on the feature branch instead and use the right metadata.

**Comment by joshghent** [comment]
> Thanks @joshghent for the report.
> 
> The Action looks for the current branch metadata, as far as I can tell, your pull-request checks runs on `main` (`master`) but should be running on the feature-branch instead. Try this:
> 
> ```
> on:
>   push:
>     branches:
>       - '**'
>       - '!main'
> ```
> 
> That'll run the PR on the feature branch instead and use the right metadata.

Will the action not be triggering off the `pull_request` condition? Will it pick up the branch metadata from that?

**Comment by PatrickHeneise** [comment]
`pull_request` triggers, but it doesn't set the right branch in the Cloudflare trigger. I'm not 100% sure, but that's the only difference I can spot to how I'm using the Action myself: https://github.com/zentered/cloudflare-preview-url/blob/main/src/cloudflare.js#L55

**Comment by joshghent** [comment]
> `pull_request` triggers, but it doesn't set the right branch in the Cloudflare trigger. I'm not 100% sure, but that's the only difference I can spot to how I'm using the Action myself: https://github.com/zentered/cloudflare-preview-url/blob/main/src/cloudflare.js#L55

Very strange but that has worked! I can submit a PR to document this quirk if you like :)
Thanks for your direct support. You really went above and beyond. Hope you have a great winter break!

**Comment by PatrickHeneise** [comment]
You'll probably need to use `master` or rename your base branch to `main`

**Pull request merged**
